name: checkout sample

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'confirm git pull'
      run: |
        which snap
        sudo snap install yq
        yq --version
        git clone https://github.com/hamadakafu/argocd-sample.git
        cd argocd-sample
        git remote set-url --push origin https://hamadakafu:${{ secrets.SAMPLE_GITHUB_TOKEN }}@github.com/hamadakafu/argocd-sample
        ls -lat
        git log --oneline

