name: CI

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1.2.0
        with:
          kubectl: 1.16.2
          kustomize: 3.4.0
          helm: 3.0.0
          command: |
            helm version
