name: checkout sample

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'confirm git pull'
      run: |
        mkdir hamadakafu_argocd-sample
        cd hamadakfu_argocd-sample
        git init
        git remote set-url --push origin https://hamadakafu:${{ secrets.SAMPLE_GITHUB_TOKEN }}@github.com/hamadakafu/argocd-sample
        git pull
        ls -lat
        git log --oneline

