name: checkout sample

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@master
    - name: echo in docker
      uses: docker://alpine:3.10
      env:
        HOGE: hogehoge
      with:
        entrypoint: /bin/sh -c
        args: |
          echo hoge && \
          echo ${HOGE}

